# PostgreSQL Server - SQL Database
version: '3.8'

# Service definition
services:
  dbPostgre:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgreVolume:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgAdminVolume:/var/lib/pgadmin4/storage
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.200
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "app@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "app"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  postgreVolume:
    name: postgreVolume
  pgAdminVolume:
    name: pgadminVolume