#!/bin/bash
set -e

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --host "$POSTGRES_HOST" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER DB_USER WITH ENCRYPTED PASSWORD 'DB_PASSWORD';
    CREATE DATABASE DB_NAME;

    GRANT ALL PRIVILEGES ON DATABASE DB_NAME TO DB_USER;

    \connect DB_NAME;
    CREATE SCHEMA IF NOT EXISTS DB_SCHEMA;
    DROP SCHEMA IF EXISTS public;

    GRANT ALL ON SCHEMA DB_SCHEMA TO DB_USER;
    ALTER USER DB_USER CREATEDB;
EOSQL